# Generated by Django 3.2.9 on 2021-12-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('-created',), 'verbose_name': 'Сниппет', 'verbose_name_plural': 'Сниппеты'},
        ),
    ]
